# Copyright 2026 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence Python Client GitHub Actions Scheduled Macaron Scan
# ---------------------------------------------------------------------------
name: Scheduled Macaron Scan

on:
  workflow_dispatch:
  schedule:
    # Every day at 1AM
    - cron: '0 1 * * *'

jobs:
  macaron-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
      artifact-metadata: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Run Macaron Security Analysis Action
        uses: oracle/macaron@v0.22.0
        with:
          repo_path: .
          policy_purl: check-github-actions
          output_dir: 'macaron-output'
          upload_attestation: false
